services:
  next:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./
        target: /app/
      - type: volume
        source: node_modules
        target: /app/node_modules/
    stdin_open: true
    tty: true

volumes:
  node_modules:
